// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.game.proto;

public interface ErrorMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.ErrorMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>int32 errorCode = 1;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <pre>
   * 错误描述
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * 错误描述
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * 详细信息
   * </pre>
   *
   * <code>string details = 3;</code>
   * @return The details.
   */
  java.lang.String getDetails();
  /**
   * <pre>
   * 详细信息
   * </pre>
   *
   * <code>string details = 3;</code>
   * @return The bytes for details.
   */
  com.google.protobuf.ByteString
      getDetailsBytes();
}
