// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.game.proto;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_GameMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_GameMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_HeartbeatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_HeartbeatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_ErrorMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_ErrorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\022\ngame.proto\"<\n\013GameMessage\022" +
      "\r\n\005msgId\030\001 \001(\005\022\020\n\010sequence\030\002 \001(\005\022\014\n\004data" +
      "\030\003 \001(\014\"6\n\020HeartbeatMessage\022\021\n\ttimestamp\030" +
      "\001 \001(\003\022\017\n\007message\030\002 \001(\t\"H\n\014ErrorMessage\022\021" +
      "\n\terrorCode\030\001 \001(\005\022\024\n\014errorMessage\030\002 \001(\t\022" +
      "\017\n\007details\030\003 \001(\t*\213\001\n\016ResponseStatus\022\013\n\007S" +
      "UCCESS\020\000\022\n\n\006FAILED\020\001\022\t\n\005ERROR\020\002\022\021\n\rINVAL" +
      "ID_PARAM\020\003\022\025\n\021PERMISSION_DENIED\020\004\022\022\n\016USE" +
      "R_NOT_FOUND\020\005\022\027\n\023USER_ALREADY_ONLINE\020\006B\022" +
      "\n\016com.game.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_game_proto_GameMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_game_proto_GameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_GameMessage_descriptor,
        new java.lang.String[] { "MsgId", "Sequence", "Data", });
    internal_static_game_proto_HeartbeatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_game_proto_HeartbeatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_HeartbeatMessage_descriptor,
        new java.lang.String[] { "Timestamp", "Message", });
    internal_static_game_proto_ErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_game_proto_ErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_ErrorMessage_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", "Details", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
