// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.game.proto;

public interface GameMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.GameMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>int32 msgId = 1;</code>
   * @return The msgId.
   */
  int getMsgId();

  /**
   * <pre>
   * 消息序列号
   * </pre>
   *
   * <code>int32 sequence = 2;</code>
   * @return The sequence.
   */
  int getSequence();

  /**
   * <pre>
   * 消息数据
   * </pre>
   *
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
