// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.game.proto;

public interface Test_ReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.Test_Req)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req = 1;</code>
   * @return The req.
   */
  java.lang.String getReq();
  /**
   * <code>string req = 1;</code>
   * @return The bytes for req.
   */
  com.google.protobuf.ByteString
      getReqBytes();
}
