// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.game.proto;

public interface Test_ResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.Test_Res)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string res = 1;</code>
   * @return The res.
   */
  java.lang.String getRes();
  /**
   * <code>string res = 1;</code>
   * @return The bytes for res.
   */
  com.google.protobuf.ByteString
      getResBytes();
}
