// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 响应状态
   * </pre>
   *
   * <code>.game.proto.ResponseStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * 响应状态
   * </pre>
   *
   * <code>.game.proto.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.game.proto.ResponseStatus getStatus();

  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
