// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

/**
 * <pre>
 * 聊天消息广播
 * </pre>
 *
 * Protobuf type {@code game.proto.login.ChatBroadcast}
 */
public final class ChatBroadcast extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game.proto.login.ChatBroadcast)
    ChatBroadcastOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatBroadcast.newBuilder() to construct.
  private ChatBroadcast(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatBroadcast() {
    fromUsername_ = "";
    content_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatBroadcast();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game.proto.login.Login.internal_static_game_proto_login_ChatBroadcast_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game.proto.login.Login.internal_static_game_proto_login_ChatBroadcast_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game.proto.login.ChatBroadcast.class, com.game.proto.login.ChatBroadcast.Builder.class);
  }

  public static final int MESSAGEID_FIELD_NUMBER = 1;
  private long messageId_ = 0L;
  /**
   * <pre>
   * 消息ID
   * </pre>
   *
   * <code>int64 messageId = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public long getMessageId() {
    return messageId_;
  }

  public static final int CHATTYPE_FIELD_NUMBER = 2;
  private int chatType_ = 0;
  /**
   * <pre>
   * 聊天类型
   * </pre>
   *
   * <code>int32 chatType = 2;</code>
   * @return The chatType.
   */
  @java.lang.Override
  public int getChatType() {
    return chatType_;
  }

  public static final int FROMUSERID_FIELD_NUMBER = 3;
  private long fromUserId_ = 0L;
  /**
   * <pre>
   * 发送者用户ID
   * </pre>
   *
   * <code>int64 fromUserId = 3;</code>
   * @return The fromUserId.
   */
  @java.lang.Override
  public long getFromUserId() {
    return fromUserId_;
  }

  public static final int FROMUSERNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fromUsername_ = "";
  /**
   * <pre>
   * 发送者用户名
   * </pre>
   *
   * <code>string fromUsername = 4;</code>
   * @return The fromUsername.
   */
  @java.lang.Override
  public java.lang.String getFromUsername() {
    java.lang.Object ref = fromUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromUsername_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发送者用户名
   * </pre>
   *
   * <code>string fromUsername = 4;</code>
   * @return The bytes for fromUsername.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromUsernameBytes() {
    java.lang.Object ref = fromUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 发送时间戳
   * </pre>
   *
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int TARGETUSERID_FIELD_NUMBER = 7;
  private long targetUserId_ = 0L;
  /**
   * <pre>
   * 目标用户ID（私聊时使用）
   * </pre>
   *
   * <code>int64 targetUserId = 7;</code>
   * @return The targetUserId.
   */
  @java.lang.Override
  public long getTargetUserId() {
    return targetUserId_;
  }

  public static final int GUILDID_FIELD_NUMBER = 8;
  private long guildId_ = 0L;
  /**
   * <pre>
   * 公会ID（公会聊天时使用）
   * </pre>
   *
   * <code>int64 guildId = 8;</code>
   * @return The guildId.
   */
  @java.lang.Override
  public long getGuildId() {
    return guildId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageId_ != 0L) {
      output.writeInt64(1, messageId_);
    }
    if (chatType_ != 0) {
      output.writeInt32(2, chatType_);
    }
    if (fromUserId_ != 0L) {
      output.writeInt64(3, fromUserId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUsername_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromUsername_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    if (targetUserId_ != 0L) {
      output.writeInt64(7, targetUserId_);
    }
    if (guildId_ != 0L) {
      output.writeInt64(8, guildId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, messageId_);
    }
    if (chatType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, chatType_);
    }
    if (fromUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, fromUserId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUsername_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromUsername_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    if (targetUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, targetUserId_);
    }
    if (guildId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, guildId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game.proto.login.ChatBroadcast)) {
      return super.equals(obj);
    }
    com.game.proto.login.ChatBroadcast other = (com.game.proto.login.ChatBroadcast) obj;

    if (getMessageId()
        != other.getMessageId()) return false;
    if (getChatType()
        != other.getChatType()) return false;
    if (getFromUserId()
        != other.getFromUserId()) return false;
    if (!getFromUsername()
        .equals(other.getFromUsername())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getTargetUserId()
        != other.getTargetUserId()) return false;
    if (getGuildId()
        != other.getGuildId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageId());
    hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChatType();
    hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFromUserId());
    hash = (37 * hash) + FROMUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFromUsername().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + TARGETUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTargetUserId());
    hash = (37 * hash) + GUILDID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGuildId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game.proto.login.ChatBroadcast parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game.proto.login.ChatBroadcast parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game.proto.login.ChatBroadcast parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game.proto.login.ChatBroadcast parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game.proto.login.ChatBroadcast prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 聊天消息广播
   * </pre>
   *
   * Protobuf type {@code game.proto.login.ChatBroadcast}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.proto.login.ChatBroadcast)
      com.game.proto.login.ChatBroadcastOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.login.Login.internal_static_game_proto_login_ChatBroadcast_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.login.Login.internal_static_game_proto_login_ChatBroadcast_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.login.ChatBroadcast.class, com.game.proto.login.ChatBroadcast.Builder.class);
    }

    // Construct using com.game.proto.login.ChatBroadcast.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageId_ = 0L;
      chatType_ = 0;
      fromUserId_ = 0L;
      fromUsername_ = "";
      content_ = "";
      timestamp_ = 0L;
      targetUserId_ = 0L;
      guildId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game.proto.login.Login.internal_static_game_proto_login_ChatBroadcast_descriptor;
    }

    @java.lang.Override
    public com.game.proto.login.ChatBroadcast getDefaultInstanceForType() {
      return com.game.proto.login.ChatBroadcast.getDefaultInstance();
    }

    @java.lang.Override
    public com.game.proto.login.ChatBroadcast build() {
      com.game.proto.login.ChatBroadcast result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game.proto.login.ChatBroadcast buildPartial() {
      com.game.proto.login.ChatBroadcast result = new com.game.proto.login.ChatBroadcast(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game.proto.login.ChatBroadcast result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chatType_ = chatType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.fromUserId_ = fromUserId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fromUsername_ = fromUsername_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.targetUserId_ = targetUserId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.guildId_ = guildId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game.proto.login.ChatBroadcast) {
        return mergeFrom((com.game.proto.login.ChatBroadcast)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game.proto.login.ChatBroadcast other) {
      if (other == com.game.proto.login.ChatBroadcast.getDefaultInstance()) return this;
      if (other.getMessageId() != 0L) {
        setMessageId(other.getMessageId());
      }
      if (other.getChatType() != 0) {
        setChatType(other.getChatType());
      }
      if (other.getFromUserId() != 0L) {
        setFromUserId(other.getFromUserId());
      }
      if (!other.getFromUsername().isEmpty()) {
        fromUsername_ = other.fromUsername_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getTargetUserId() != 0L) {
        setTargetUserId(other.getTargetUserId());
      }
      if (other.getGuildId() != 0L) {
        setGuildId(other.getGuildId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              chatType_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              fromUserId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              fromUsername_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              targetUserId_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              guildId_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long messageId_ ;
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>int64 messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>int64 messageId = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(long value) {

      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>int64 messageId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageId_ = 0L;
      onChanged();
      return this;
    }

    private int chatType_ ;
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>int32 chatType = 2;</code>
     * @return The chatType.
     */
    @java.lang.Override
    public int getChatType() {
      return chatType_;
    }
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>int32 chatType = 2;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(int value) {

      chatType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>int32 chatType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      chatType_ = 0;
      onChanged();
      return this;
    }

    private long fromUserId_ ;
    /**
     * <pre>
     * 发送者用户ID
     * </pre>
     *
     * <code>int64 fromUserId = 3;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public long getFromUserId() {
      return fromUserId_;
    }
    /**
     * <pre>
     * 发送者用户ID
     * </pre>
     *
     * <code>int64 fromUserId = 3;</code>
     * @param value The fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserId(long value) {

      fromUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者用户ID
     * </pre>
     *
     * <code>int64 fromUserId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUserId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      fromUserId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fromUsername_ = "";
    /**
     * <pre>
     * 发送者用户名
     * </pre>
     *
     * <code>string fromUsername = 4;</code>
     * @return The fromUsername.
     */
    public java.lang.String getFromUsername() {
      java.lang.Object ref = fromUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 发送者用户名
     * </pre>
     *
     * <code>string fromUsername = 4;</code>
     * @return The bytes for fromUsername.
     */
    public com.google.protobuf.ByteString
        getFromUsernameBytes() {
      java.lang.Object ref = fromUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发送者用户名
     * </pre>
     *
     * <code>string fromUsername = 4;</code>
     * @param value The fromUsername to set.
     * @return This builder for chaining.
     */
    public Builder setFromUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fromUsername_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者用户名
     * </pre>
     *
     * <code>string fromUsername = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUsername() {
      fromUsername_ = getDefaultInstance().getFromUsername();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者用户名
     * </pre>
     *
     * <code>string fromUsername = 4;</code>
     * @param value The bytes for fromUsername to set.
     * @return This builder for chaining.
     */
    public Builder setFromUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fromUsername_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 发送时间戳
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 发送时间戳
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送时间戳
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long targetUserId_ ;
    /**
     * <pre>
     * 目标用户ID（私聊时使用）
     * </pre>
     *
     * <code>int64 targetUserId = 7;</code>
     * @return The targetUserId.
     */
    @java.lang.Override
    public long getTargetUserId() {
      return targetUserId_;
    }
    /**
     * <pre>
     * 目标用户ID（私聊时使用）
     * </pre>
     *
     * <code>int64 targetUserId = 7;</code>
     * @param value The targetUserId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetUserId(long value) {

      targetUserId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标用户ID（私聊时使用）
     * </pre>
     *
     * <code>int64 targetUserId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetUserId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      targetUserId_ = 0L;
      onChanged();
      return this;
    }

    private long guildId_ ;
    /**
     * <pre>
     * 公会ID（公会聊天时使用）
     * </pre>
     *
     * <code>int64 guildId = 8;</code>
     * @return The guildId.
     */
    @java.lang.Override
    public long getGuildId() {
      return guildId_;
    }
    /**
     * <pre>
     * 公会ID（公会聊天时使用）
     * </pre>
     *
     * <code>int64 guildId = 8;</code>
     * @param value The guildId to set.
     * @return This builder for chaining.
     */
    public Builder setGuildId(long value) {

      guildId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 公会ID（公会聊天时使用）
     * </pre>
     *
     * <code>int64 guildId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearGuildId() {
      bitField0_ = (bitField0_ & ~0x00000080);
      guildId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game.proto.login.ChatBroadcast)
  }

  // @@protoc_insertion_point(class_scope:game.proto.login.ChatBroadcast)
  private static final com.game.proto.login.ChatBroadcast DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game.proto.login.ChatBroadcast();
  }

  public static com.game.proto.login.ChatBroadcast getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatBroadcast>
      PARSER = new com.google.protobuf.AbstractParser<ChatBroadcast>() {
    @java.lang.Override
    public ChatBroadcast parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatBroadcast> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatBroadcast> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game.proto.login.ChatBroadcast getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

