// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface ChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.ChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 聊天类型 (1:世界, 2:私聊, 3:公会)
   * </pre>
   *
   * <code>int32 chatType = 1;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 目标用户ID（私聊时使用）
   * </pre>
   *
   * <code>int64 targetUserId = 3;</code>
   * @return The targetUserId.
   */
  long getTargetUserId();

  /**
   * <pre>
   * 公会ID（公会聊天时使用）
   * </pre>
   *
   * <code>int64 guildId = 4;</code>
   * @return The guildId.
   */
  long getGuildId();
}
