// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface ChatBroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.ChatBroadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息ID
   * </pre>
   *
   * <code>int64 messageId = 1;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <pre>
   * 聊天类型
   * </pre>
   *
   * <code>int32 chatType = 2;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <pre>
   * 发送者用户ID
   * </pre>
   *
   * <code>int64 fromUserId = 3;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <pre>
   * 发送者用户名
   * </pre>
   *
   * <code>string fromUsername = 4;</code>
   * @return The fromUsername.
   */
  java.lang.String getFromUsername();
  /**
   * <pre>
   * 发送者用户名
   * </pre>
   *
   * <code>string fromUsername = 4;</code>
   * @return The bytes for fromUsername.
   */
  com.google.protobuf.ByteString
      getFromUsernameBytes();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 发送时间戳
   * </pre>
   *
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 目标用户ID（私聊时使用）
   * </pre>
   *
   * <code>int64 targetUserId = 7;</code>
   * @return The targetUserId.
   */
  long getTargetUserId();

  /**
   * <pre>
   * 公会ID（公会聊天时使用）
   * </pre>
   *
   * <code>int64 guildId = 8;</code>
   * @return The guildId.
   */
  long getGuildId();
}
