// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface CS_player_loginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.CS_player_login)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * 服务器索引
   * </pre>
   *
   * <code>int32 serverIndex = 2;</code>
   * @return The serverIndex.
   */
  int getServerIndex();

  /**
   * <pre>
   * 客户端版本
   * </pre>
   *
   * <code>string clientVersion = 3;</code>
   * @return The clientVersion.
   */
  java.lang.String getClientVersion();
  /**
   * <pre>
   * 客户端版本
   * </pre>
   *
   * <code>string clientVersion = 3;</code>
   * @return The bytes for clientVersion.
   */
  com.google.protobuf.ByteString
      getClientVersionBytes();

  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string deviceId = 4;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string deviceId = 4;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   *ip
   * </pre>
   *
   * <code>string ip = 5;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <pre>
   *ip
   * </pre>
   *
   * <code>string ip = 5;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   *角色名
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *角色名
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
