// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_CS_player_login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_CS_player_login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_SC_create_role_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_SC_create_role_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_SC_player_login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_SC_player_login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_UserInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_UserInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_UserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_UserInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_UserUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_UserUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_UserUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_UserUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_ChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_ChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_ChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_ChatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_ChatBroadcast_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_ChatBroadcast_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_proto_login_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_proto_login_LogoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022\020game.proto.login\032\ngame.pr" +
      "oto\"y\n\017CS_player_login\022\016\n\006userId\030\001 \001(\t\022\023" +
      "\n\013serverIndex\030\002 \001(\005\022\025\n\rclientVersion\030\003 \001" +
      "(\t\022\020\n\010deviceId\030\004 \001(\t\022\n\n\002ip\030\005 \001(\t\022\014\n\004name" +
      "\030\006 \001(\t\" \n\016SC_create_role\022\016\n\006result\030\001 \001(\005" +
      "\"Y\n\017SC_player_login\022\020\n\010playerId\030\001 \001(\003\022\023\n" +
      "\013serverIndex\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\021\n\tcrea" +
      "tenum\030\004 \001(\005\"\223\001\n\010UserInfo\022\016\n\006userId\030\001 \001(\003" +
      "\022\020\n\010username\030\002 \001(\t\022\r\n\005level\030\003 \001(\005\022\014\n\004gol" +
      "d\030\004 \001(\003\022\013\n\003exp\030\005 \001(\003\022\022\n\ncreateTime\030\006 \001(\003" +
      "\022\025\n\rlastLoginTime\030\007 \001(\003\022\020\n\010isOnline\030\010 \001(" +
      "\010\"!\n\017UserInfoRequest\022\016\n\006userId\030\001 \001(\003\"}\n\020" +
      "UserInfoResponse\022*\n\006status\030\001 \001(\0162\032.game." +
      "proto.ResponseStatus\022\017\n\007message\030\002 \001(\t\022,\n" +
      "\010userInfo\030\003 \001(\0132\032.game.proto.login.UserI" +
      "nfo\"w\n\021UserUpdateRequest\022\016\n\006userId\030\001 \001(\003" +
      "\022\022\n\005level\030\002 \001(\005H\000\210\001\001\022\021\n\004gold\030\003 \001(\003H\001\210\001\001\022" +
      "\020\n\003exp\030\004 \001(\003H\002\210\001\001B\010\n\006_levelB\007\n\005_goldB\006\n\004" +
      "_exp\"\177\n\022UserUpdateResponse\022*\n\006status\030\001 \001" +
      "(\0162\032.game.proto.ResponseStatus\022\017\n\007messag" +
      "e\030\002 \001(\t\022,\n\010userInfo\030\003 \001(\0132\032.game.proto.l" +
      "ogin.UserInfo\"W\n\013ChatRequest\022\020\n\010chatType" +
      "\030\001 \001(\005\022\017\n\007content\030\002 \001(\t\022\024\n\014targetUserId\030" +
      "\003 \001(\003\022\017\n\007guildId\030\004 \001(\003\"K\n\014ChatResponse\022*" +
      "\n\006status\030\001 \001(\0162\032.game.proto.ResponseStat" +
      "us\022\017\n\007message\030\002 \001(\t\"\251\001\n\rChatBroadcast\022\021\n" +
      "\tmessageId\030\001 \001(\003\022\020\n\010chatType\030\002 \001(\005\022\022\n\nfr" +
      "omUserId\030\003 \001(\003\022\024\n\014fromUsername\030\004 \001(\t\022\017\n\007" +
      "content\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\003\022\024\n\014targ" +
      "etUserId\030\007 \001(\003\022\017\n\007guildId\030\010 \001(\003\"/\n\rLogou" +
      "tRequest\022\016\n\006userId\030\001 \001(\003\022\016\n\006reason\030\002 \001(\t" +
      "\"M\n\016LogoutResponse\022*\n\006status\030\001 \001(\0162\032.gam" +
      "e.proto.ResponseStatus\022\017\n\007message\030\002 \001(\tB" +
      "\030\n\024com.game.proto.loginP\001P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.proto.Game.getDescriptor(),
        });
    internal_static_game_proto_login_CS_player_login_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_game_proto_login_CS_player_login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_CS_player_login_descriptor,
        new java.lang.String[] { "UserId", "ServerIndex", "ClientVersion", "DeviceId", "Ip", "Name", });
    internal_static_game_proto_login_SC_create_role_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_game_proto_login_SC_create_role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_SC_create_role_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_game_proto_login_SC_player_login_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_game_proto_login_SC_player_login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_SC_player_login_descriptor,
        new java.lang.String[] { "PlayerId", "ServerIndex", "Name", "Createnum", });
    internal_static_game_proto_login_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_game_proto_login_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_UserInfo_descriptor,
        new java.lang.String[] { "UserId", "Username", "Level", "Gold", "Exp", "CreateTime", "LastLoginTime", "IsOnline", });
    internal_static_game_proto_login_UserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_game_proto_login_UserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_UserInfoRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_game_proto_login_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_game_proto_login_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_UserInfoResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "UserInfo", });
    internal_static_game_proto_login_UserUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_game_proto_login_UserUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_UserUpdateRequest_descriptor,
        new java.lang.String[] { "UserId", "Level", "Gold", "Exp", "Level", "Gold", "Exp", });
    internal_static_game_proto_login_UserUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_game_proto_login_UserUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_UserUpdateResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "UserInfo", });
    internal_static_game_proto_login_ChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_game_proto_login_ChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_ChatRequest_descriptor,
        new java.lang.String[] { "ChatType", "Content", "TargetUserId", "GuildId", });
    internal_static_game_proto_login_ChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_game_proto_login_ChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_ChatResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_game_proto_login_ChatBroadcast_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_game_proto_login_ChatBroadcast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_ChatBroadcast_descriptor,
        new java.lang.String[] { "MessageId", "ChatType", "FromUserId", "FromUsername", "Content", "Timestamp", "TargetUserId", "GuildId", });
    internal_static_game_proto_login_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_game_proto_login_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_LogoutRequest_descriptor,
        new java.lang.String[] { "UserId", "Reason", });
    internal_static_game_proto_login_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_game_proto_login_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_proto_login_LogoutResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    com.game.proto.Game.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
