// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <pre>
   * 登出原因
   * </pre>
   *
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <pre>
   * 登出原因
   * </pre>
   *
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
