// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface SC_create_roleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.SC_create_role)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *是否创角 1是 0否
   * </pre>
   *
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();
}
