// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface SC_player_loginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.SC_player_login)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 playerId = 1;</code>
   * @return The playerId.
   */
  long getPlayerId();

  /**
   * <code>int32 serverIndex = 2;</code>
   * @return The serverIndex.
   */
  int getServerIndex();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 createnum = 4;</code>
   * @return The createnum.
   */
  int getCreatenum();
}
