// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * 金币
   * </pre>
   *
   * <code>int64 gold = 4;</code>
   * @return The gold.
   */
  long getGold();

  /**
   * <pre>
   * 经验值
   * </pre>
   *
   * <code>int64 exp = 5;</code>
   * @return The exp.
   */
  long getExp();

  /**
   * <pre>
   * 创建时间
   * </pre>
   *
   * <code>int64 createTime = 6;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   * 最后登录时间
   * </pre>
   *
   * <code>int64 lastLoginTime = 7;</code>
   * @return The lastLoginTime.
   */
  long getLastLoginTime();

  /**
   * <pre>
   * 是否在线
   * </pre>
   *
   * <code>bool isOnline = 8;</code>
   * @return The isOnline.
   */
  boolean getIsOnline();
}
