// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

/**
 * <pre>
 * 用户更新请求
 * </pre>
 *
 * Protobuf type {@code game.proto.login.UserUpdateRequest}
 */
public final class UserUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game.proto.login.UserUpdateRequest)
    UserUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserUpdateRequest.newBuilder() to construct.
  private UserUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserUpdateRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserUpdateRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game.proto.login.Login.internal_static_game_proto_login_UserUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game.proto.login.Login.internal_static_game_proto_login_UserUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game.proto.login.UserUpdateRequest.class, com.game.proto.login.UserUpdateRequest.Builder.class);
  }

  private int bitField0_;
  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int LEVEL_FIELD_NUMBER = 2;
  private int level_ = 0;
  /**
   * <pre>
   * 等级（可选）
   * </pre>
   *
   * <code>optional int32 level = 2;</code>
   * @return Whether the level field is set.
   */
  @java.lang.Override
  public boolean hasLevel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 等级（可选）
   * </pre>
   *
   * <code>optional int32 level = 2;</code>
   * @return The level.
   */
  @java.lang.Override
  public int getLevel() {
    return level_;
  }

  public static final int GOLD_FIELD_NUMBER = 3;
  private long gold_ = 0L;
  /**
   * <pre>
   * 金币（可选）
   * </pre>
   *
   * <code>optional int64 gold = 3;</code>
   * @return Whether the gold field is set.
   */
  @java.lang.Override
  public boolean hasGold() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 金币（可选）
   * </pre>
   *
   * <code>optional int64 gold = 3;</code>
   * @return The gold.
   */
  @java.lang.Override
  public long getGold() {
    return gold_;
  }

  public static final int EXP_FIELD_NUMBER = 4;
  private long exp_ = 0L;
  /**
   * <pre>
   * 经验值（可选）
   * </pre>
   *
   * <code>optional int64 exp = 4;</code>
   * @return Whether the exp field is set.
   */
  @java.lang.Override
  public boolean hasExp() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 经验值（可选）
   * </pre>
   *
   * <code>optional int64 exp = 4;</code>
   * @return The exp.
   */
  @java.lang.Override
  public long getExp() {
    return exp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, level_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(3, gold_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(4, exp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, level_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, gold_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, exp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game.proto.login.UserUpdateRequest)) {
      return super.equals(obj);
    }
    com.game.proto.login.UserUpdateRequest other = (com.game.proto.login.UserUpdateRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (hasLevel() != other.hasLevel()) return false;
    if (hasLevel()) {
      if (getLevel()
          != other.getLevel()) return false;
    }
    if (hasGold() != other.hasGold()) return false;
    if (hasGold()) {
      if (getGold()
          != other.getGold()) return false;
    }
    if (hasExp() != other.hasExp()) return false;
    if (hasExp()) {
      if (getExp()
          != other.getExp()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    if (hasLevel()) {
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
    }
    if (hasGold()) {
      hash = (37 * hash) + GOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGold());
    }
    if (hasExp()) {
      hash = (37 * hash) + EXP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExp());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game.proto.login.UserUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game.proto.login.UserUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game.proto.login.UserUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game.proto.login.UserUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game.proto.login.UserUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户更新请求
   * </pre>
   *
   * Protobuf type {@code game.proto.login.UserUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.proto.login.UserUpdateRequest)
      com.game.proto.login.UserUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.login.Login.internal_static_game_proto_login_UserUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.login.Login.internal_static_game_proto_login_UserUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.login.UserUpdateRequest.class, com.game.proto.login.UserUpdateRequest.Builder.class);
    }

    // Construct using com.game.proto.login.UserUpdateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      level_ = 0;
      gold_ = 0L;
      exp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game.proto.login.Login.internal_static_game_proto_login_UserUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.game.proto.login.UserUpdateRequest getDefaultInstanceForType() {
      return com.game.proto.login.UserUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.game.proto.login.UserUpdateRequest build() {
      com.game.proto.login.UserUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game.proto.login.UserUpdateRequest buildPartial() {
      com.game.proto.login.UserUpdateRequest result = new com.game.proto.login.UserUpdateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game.proto.login.UserUpdateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.level_ = level_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gold_ = gold_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.exp_ = exp_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game.proto.login.UserUpdateRequest) {
        return mergeFrom((com.game.proto.login.UserUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game.proto.login.UserUpdateRequest other) {
      if (other == com.game.proto.login.UserUpdateRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.hasLevel()) {
        setLevel(other.getLevel());
      }
      if (other.hasGold()) {
        setGold(other.getGold());
      }
      if (other.hasExp()) {
        setExp(other.getExp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              level_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              gold_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              exp_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <pre>
     * 等级（可选）
     * </pre>
     *
     * <code>optional int32 level = 2;</code>
     * @return Whether the level field is set.
     */
    @java.lang.Override
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 等级（可选）
     * </pre>
     *
     * <code>optional int32 level = 2;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }
    /**
     * <pre>
     * 等级（可选）
     * </pre>
     *
     * <code>optional int32 level = 2;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {

      level_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 等级（可选）
     * </pre>
     *
     * <code>optional int32 level = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      level_ = 0;
      onChanged();
      return this;
    }

    private long gold_ ;
    /**
     * <pre>
     * 金币（可选）
     * </pre>
     *
     * <code>optional int64 gold = 3;</code>
     * @return Whether the gold field is set.
     */
    @java.lang.Override
    public boolean hasGold() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 金币（可选）
     * </pre>
     *
     * <code>optional int64 gold = 3;</code>
     * @return The gold.
     */
    @java.lang.Override
    public long getGold() {
      return gold_;
    }
    /**
     * <pre>
     * 金币（可选）
     * </pre>
     *
     * <code>optional int64 gold = 3;</code>
     * @param value The gold to set.
     * @return This builder for chaining.
     */
    public Builder setGold(long value) {

      gold_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 金币（可选）
     * </pre>
     *
     * <code>optional int64 gold = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGold() {
      bitField0_ = (bitField0_ & ~0x00000004);
      gold_ = 0L;
      onChanged();
      return this;
    }

    private long exp_ ;
    /**
     * <pre>
     * 经验值（可选）
     * </pre>
     *
     * <code>optional int64 exp = 4;</code>
     * @return Whether the exp field is set.
     */
    @java.lang.Override
    public boolean hasExp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 经验值（可选）
     * </pre>
     *
     * <code>optional int64 exp = 4;</code>
     * @return The exp.
     */
    @java.lang.Override
    public long getExp() {
      return exp_;
    }
    /**
     * <pre>
     * 经验值（可选）
     * </pre>
     *
     * <code>optional int64 exp = 4;</code>
     * @param value The exp to set.
     * @return This builder for chaining.
     */
    public Builder setExp(long value) {

      exp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 经验值（可选）
     * </pre>
     *
     * <code>optional int64 exp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearExp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      exp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game.proto.login.UserUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:game.proto.login.UserUpdateRequest)
  private static final com.game.proto.login.UserUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game.proto.login.UserUpdateRequest();
  }

  public static com.game.proto.login.UserUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<UserUpdateRequest>() {
    @java.lang.Override
    public UserUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game.proto.login.UserUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

