// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface UserUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.UserUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <pre>
   * 等级（可选）
   * </pre>
   *
   * <code>optional int32 level = 2;</code>
   * @return Whether the level field is set.
   */
  boolean hasLevel();
  /**
   * <pre>
   * 等级（可选）
   * </pre>
   *
   * <code>optional int32 level = 2;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * 金币（可选）
   * </pre>
   *
   * <code>optional int64 gold = 3;</code>
   * @return Whether the gold field is set.
   */
  boolean hasGold();
  /**
   * <pre>
   * 金币（可选）
   * </pre>
   *
   * <code>optional int64 gold = 3;</code>
   * @return The gold.
   */
  long getGold();

  /**
   * <pre>
   * 经验值（可选）
   * </pre>
   *
   * <code>optional int64 exp = 4;</code>
   * @return Whether the exp field is set.
   */
  boolean hasExp();
  /**
   * <pre>
   * 经验值（可选）
   * </pre>
   *
   * <code>optional int64 exp = 4;</code>
   * @return The exp.
   */
  long getExp();
}
