// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

/**
 * <pre>
 * 用户信息
 * </pre>
 *
 * Protobuf type {@code game.proto.login.UserInfo}
 */
public final class UserInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game.proto.login.UserInfo)
    UserInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserInfo.newBuilder() to construct.
  private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserInfo() {
    username_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game.proto.login.Login.internal_static_game_proto_login_UserInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game.proto.login.Login.internal_static_game_proto_login_UserInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game.proto.login.UserInfo.class, com.game.proto.login.UserInfo.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object username_ = "";
  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 2;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEVEL_FIELD_NUMBER = 3;
  private int level_ = 0;
  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  @java.lang.Override
  public int getLevel() {
    return level_;
  }

  public static final int GOLD_FIELD_NUMBER = 4;
  private long gold_ = 0L;
  /**
   * <pre>
   * 金币
   * </pre>
   *
   * <code>int64 gold = 4;</code>
   * @return The gold.
   */
  @java.lang.Override
  public long getGold() {
    return gold_;
  }

  public static final int EXP_FIELD_NUMBER = 5;
  private long exp_ = 0L;
  /**
   * <pre>
   * 经验值
   * </pre>
   *
   * <code>int64 exp = 5;</code>
   * @return The exp.
   */
  @java.lang.Override
  public long getExp() {
    return exp_;
  }

  public static final int CREATETIME_FIELD_NUMBER = 6;
  private long createTime_ = 0L;
  /**
   * <pre>
   * 创建时间
   * </pre>
   *
   * <code>int64 createTime = 6;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public long getCreateTime() {
    return createTime_;
  }

  public static final int LASTLOGINTIME_FIELD_NUMBER = 7;
  private long lastLoginTime_ = 0L;
  /**
   * <pre>
   * 最后登录时间
   * </pre>
   *
   * <code>int64 lastLoginTime = 7;</code>
   * @return The lastLoginTime.
   */
  @java.lang.Override
  public long getLastLoginTime() {
    return lastLoginTime_;
  }

  public static final int ISONLINE_FIELD_NUMBER = 8;
  private boolean isOnline_ = false;
  /**
   * <pre>
   * 是否在线
   * </pre>
   *
   * <code>bool isOnline = 8;</code>
   * @return The isOnline.
   */
  @java.lang.Override
  public boolean getIsOnline() {
    return isOnline_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (level_ != 0) {
      output.writeInt32(3, level_);
    }
    if (gold_ != 0L) {
      output.writeInt64(4, gold_);
    }
    if (exp_ != 0L) {
      output.writeInt64(5, exp_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(6, createTime_);
    }
    if (lastLoginTime_ != 0L) {
      output.writeInt64(7, lastLoginTime_);
    }
    if (isOnline_ != false) {
      output.writeBool(8, isOnline_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, level_);
    }
    if (gold_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, gold_);
    }
    if (exp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, exp_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, createTime_);
    }
    if (lastLoginTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, lastLoginTime_);
    }
    if (isOnline_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isOnline_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game.proto.login.UserInfo)) {
      return super.equals(obj);
    }
    com.game.proto.login.UserInfo other = (com.game.proto.login.UserInfo) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (getLevel()
        != other.getLevel()) return false;
    if (getGold()
        != other.getGold()) return false;
    if (getExp()
        != other.getExp()) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (getLastLoginTime()
        != other.getLastLoginTime()) return false;
    if (getIsOnline()
        != other.getIsOnline()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + GOLD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGold());
    hash = (37 * hash) + EXP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExp());
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + LASTLOGINTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLoginTime());
    hash = (37 * hash) + ISONLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOnline());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game.proto.login.UserInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.UserInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.UserInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.UserInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.UserInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.proto.login.UserInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.proto.login.UserInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game.proto.login.UserInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game.proto.login.UserInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game.proto.login.UserInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game.proto.login.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game.proto.login.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game.proto.login.UserInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * Protobuf type {@code game.proto.login.UserInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.proto.login.UserInfo)
      com.game.proto.login.UserInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.login.Login.internal_static_game_proto_login_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.login.Login.internal_static_game_proto_login_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.login.UserInfo.class, com.game.proto.login.UserInfo.Builder.class);
    }

    // Construct using com.game.proto.login.UserInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      username_ = "";
      level_ = 0;
      gold_ = 0L;
      exp_ = 0L;
      createTime_ = 0L;
      lastLoginTime_ = 0L;
      isOnline_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game.proto.login.Login.internal_static_game_proto_login_UserInfo_descriptor;
    }

    @java.lang.Override
    public com.game.proto.login.UserInfo getDefaultInstanceForType() {
      return com.game.proto.login.UserInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.game.proto.login.UserInfo build() {
      com.game.proto.login.UserInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game.proto.login.UserInfo buildPartial() {
      com.game.proto.login.UserInfo result = new com.game.proto.login.UserInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game.proto.login.UserInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.username_ = username_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.level_ = level_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.gold_ = gold_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.exp_ = exp_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.createTime_ = createTime_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.lastLoginTime_ = lastLoginTime_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.isOnline_ = isOnline_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game.proto.login.UserInfo) {
        return mergeFrom((com.game.proto.login.UserInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game.proto.login.UserInfo other) {
      if (other == com.game.proto.login.UserInfo.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (other.getGold() != 0L) {
        setGold(other.getGold());
      }
      if (other.getExp() != 0L) {
        setExp(other.getExp());
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getLastLoginTime() != 0L) {
        setLastLoginTime(other.getLastLoginTime());
      }
      if (other.getIsOnline() != false) {
        setIsOnline(other.getIsOnline());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              username_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              level_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              gold_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              exp_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              createTime_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              lastLoginTime_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              isOnline_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string username = 2;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string username = 2;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      username_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string username = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      username_ = getDefaultInstance().getUsername();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string username = 2;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      username_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>int32 level = 3;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>int32 level = 3;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {

      level_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>int32 level = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      level_ = 0;
      onChanged();
      return this;
    }

    private long gold_ ;
    /**
     * <pre>
     * 金币
     * </pre>
     *
     * <code>int64 gold = 4;</code>
     * @return The gold.
     */
    @java.lang.Override
    public long getGold() {
      return gold_;
    }
    /**
     * <pre>
     * 金币
     * </pre>
     *
     * <code>int64 gold = 4;</code>
     * @param value The gold to set.
     * @return This builder for chaining.
     */
    public Builder setGold(long value) {

      gold_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 金币
     * </pre>
     *
     * <code>int64 gold = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGold() {
      bitField0_ = (bitField0_ & ~0x00000008);
      gold_ = 0L;
      onChanged();
      return this;
    }

    private long exp_ ;
    /**
     * <pre>
     * 经验值
     * </pre>
     *
     * <code>int64 exp = 5;</code>
     * @return The exp.
     */
    @java.lang.Override
    public long getExp() {
      return exp_;
    }
    /**
     * <pre>
     * 经验值
     * </pre>
     *
     * <code>int64 exp = 5;</code>
     * @param value The exp to set.
     * @return This builder for chaining.
     */
    public Builder setExp(long value) {

      exp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 经验值
     * </pre>
     *
     * <code>int64 exp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      exp_ = 0L;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {

      createTime_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private long lastLoginTime_ ;
    /**
     * <pre>
     * 最后登录时间
     * </pre>
     *
     * <code>int64 lastLoginTime = 7;</code>
     * @return The lastLoginTime.
     */
    @java.lang.Override
    public long getLastLoginTime() {
      return lastLoginTime_;
    }
    /**
     * <pre>
     * 最后登录时间
     * </pre>
     *
     * <code>int64 lastLoginTime = 7;</code>
     * @param value The lastLoginTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastLoginTime(long value) {

      lastLoginTime_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最后登录时间
     * </pre>
     *
     * <code>int64 lastLoginTime = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLoginTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      lastLoginTime_ = 0L;
      onChanged();
      return this;
    }

    private boolean isOnline_ ;
    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>bool isOnline = 8;</code>
     * @return The isOnline.
     */
    @java.lang.Override
    public boolean getIsOnline() {
      return isOnline_;
    }
    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>bool isOnline = 8;</code>
     * @param value The isOnline to set.
     * @return This builder for chaining.
     */
    public Builder setIsOnline(boolean value) {

      isOnline_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>bool isOnline = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOnline() {
      bitField0_ = (bitField0_ & ~0x00000080);
      isOnline_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game.proto.login.UserInfo)
  }

  // @@protoc_insertion_point(class_scope:game.proto.login.UserInfo)
  private static final com.game.proto.login.UserInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game.proto.login.UserInfo();
  }

  public static com.game.proto.login.UserInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserInfo>
      PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
    @java.lang.Override
    public UserInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game.proto.login.UserInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

