// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface UserInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.UserInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID（可选，不填则返回当前用户信息）
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
