// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.game.proto.login;

public interface UserUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.proto.login.UserUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 响应状态
   * </pre>
   *
   * <code>.game.proto.ResponseStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * 响应状态
   * </pre>
   *
   * <code>.game.proto.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.game.proto.ResponseStatus getStatus();

  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 更新后的用户信息
   * </pre>
   *
   * <code>.game.proto.login.UserInfo userInfo = 3;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <pre>
   * 更新后的用户信息
   * </pre>
   *
   * <code>.game.proto.login.UserInfo userInfo = 3;</code>
   * @return The userInfo.
   */
  com.game.proto.login.UserInfo getUserInfo();
  /**
   * <pre>
   * 更新后的用户信息
   * </pre>
   *
   * <code>.game.proto.login.UserInfo userInfo = 3;</code>
   */
  com.game.proto.login.UserInfoOrBuilder getUserInfoOrBuilder();
}
