// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageId.proto

package com.game.proto.msgid;

public final class MessageId {
  private MessageId() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MessageId.proto\022\020game.proto.msgid*\347\003\n\t" +
      "MsgIdEnum\022\017\n\013MSG_UNKNOWN\020\000\022\035\n\030MSG_SYSTEM" +
      "_HEARTBEAT_REQ\020\350\007\022\035\n\030MSG_SYSTEM_HEARTBEA" +
      "T_RES\020\351\007\022\025\n\020MSG_SYSTEM_ERROR\020\352\007\022\014\n\007CS_te" +
      "st\020\334\013\022\014\n\007SC_test\020\335\013\022\024\n\017CS_player_login\020\320" +
      "\017\022\024\n\017SC_player_login\020\321\017\022\025\n\020CS_player_log" +
      "out\020\322\017\022\025\n\020SC_player_logout\020\323\017\022\023\n\016SC_crea" +
      "te_role\020\324\017\022\023\n\016CS_create_role\020\325\017\022\034\n\027MSG_P" +
      "LAYER_INFO_REQUEST\020\264\020\022\035\n\030MSG_PLAYER_INFO" +
      "_RESPONSE\020\265\020\022\036\n\031MSG_PLAYER_UPDATE_REQUES" +
      "T\020\266\020\022\037\n\032MSG_PLAYER_UPDATE_RESPONSE\020\267\020\022\035\n" +
      "\030MSG_CHAT_MESSAGE_REQUEST\020\270\027\022\036\n\031MSG_CHAT" +
      "_MESSAGE_RESPONSE\020\271\027\022\027\n\022MSG_CHAT_BROADCA" +
      "ST\020\272\027B\030\n\024com.game.proto.msgidP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
