spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/game_db_prod?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

# 生产环境日志配置
logging:
  level:
    root: WARN
    com.game: INFO
  file:
    name: /var/log/game-server/game-server.log

# 生产环境游戏配置
game:
  cache:
    persistence-interval: 120000   # 生产环境较长的持久化间隔
    cleanup-interval: 600000       # 生产环境较长的清理间隔
  
  # 配置文件路径
  config:
    path: game-server/config      # Excel配置文件路径（相对于项目根目录）
  
  # game-server目录路径
  server:
    path: game-server             # game-server目录路径（相对于项目根目录）